### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by vkkhare** [seung-lab/kimimaro#41] opened 2020-02-21 11:42 UTC
Hi while running this function I get segmentation fault or bus error. I would like to know the cause of this memory does not exist error.

```
     skeletons = kimimaro.skeletonize(
        cubeData, 
        teasar_params=teasar_params, 
        anisotropy=vox_size, # in nanometers
        dust_threshold=1000, # in voxels
        progress=progress,
        fix_branching=True,
        fix_borders=True, # default True
        parallel=0
    )
```
my teaser_params are
```
teasar_params = {
  # TEASAR parameters
  'scale': 4, # invalidation ball scale factor
  'const': 500, # invalidation ball const factor (in physical units)
  'pdrf_scale': 100000, # pdrf scale factor
  'pdrf_exponent': 4, # pdrf exponent

  'soma_detection_threshold': 99999999, # in physical units, set high to shut off
  'soma_acceptance_threshold': 99999999, # in physical units, set high to shut off
  'soma_invalidation_scale': 0.5, # Special invalidation ball for somata
  'soma_invalidation_const': 0, # Special invalidation ball for somata
}
```
I have soma in my dataset but they are not segmented.
Any suggestion will be of great help!
Thanks

**Comment by william-silversmith** [comment] 2020-02-21 12:40
Hi Varun,

Is it happening in the same place each time? The parameters don't seem
weird.

Will

**Comment by vkkhare** [comment] 2020-02-21 12:48
Thanks for quick reply.
The error occurs on random boxes in my dataset when I submit the job via slurm/run it as a python script. The error seems to be random because the same box sometimes runs successfully

**Comment by william-silversmith** [comment] 2020-02-21 13:00
Are you able to reproduce the error by rerunning on the same box several
times? Also, are you using the latest versions of the dependent libraries?

**Comment by vkkhare** [comment] 2020-02-21 13:19
The version of requirements are:
```
connected-components-3d==1.5.0
cloud-volume==1.6.0
dijkstra3d==1.1.0 #1.2.0 recommended
fill-voids==1.0.0
edt==2.0.0
fastremap==1.8.0
networkx==2.1
numpy==1.18.1
scipy==1.4.1 
pathos==0.2.5
pytest==5.3.5
```
The only error I can have wrt dependencies is with dijkstra. I just saw the recommended version is 1.2.0

**Comment by william-silversmith** [comment] 2020-02-21 13:22
Try running pip install kimimaro -U just to make sure we're working from
the same set of dependencies.

**Comment by vkkhare** [comment] 2020-02-21 13:45
I will get back to you after testing on the new dependencies

**Comment by william-silversmith** [comment] 2020-02-21 14:04
If you're able to share with me some of the data that's causing errors, that would be a big help.  What OS is the system you're running on?

**Comment by vkkhare** [comment] 2020-02-21 14:09
I am using CentOS Linux release 7.5.1804 (Core). The compute nodes have 192G memory and the tasks have a voxel grid of `3744, 3744, 852` with labels `1` and `0`. I have rerun the script and am awaiting if any error is thrown. I will link that with you!

**Comment by william-silversmith** [comment] 2020-02-21 14:16
Wow... That's quite a bit bigger than the largest size I've tested with. I think some of the libraries get fickle when the size gets above a few GB. I can try testing, but I probably won't have an answer today. 

Would you be able to downsample your volume? If some of the detail isn't critical, you can process a much smaller volume. You could try using the segmentation downsample in https://github.com/seung-lab/tinybrain/

**Comment by william-silversmith** [comment] 2020-02-21 14:17
Alternatively, you could try skeletonizing a smaller size (e.g. 512x512x512) and stitching. Kimimaro was designed for that if you use 1 voxel overlaps.

**Comment by vkkhare** [comment] 2020-02-21 14:36
Ahh I see, I cannot downsample my volume but can stitch the smaller boxes though it will make things slower. I have over 4000 such boxes :(

**Comment by william-silversmith** [comment] 2020-02-21 17:01
If you use smaller boxes, you can use more parallelism. Have you seen
github.com/seung-lab/igneous ? You can either use it directly or crib code
from it. Sorry for the inconvenience....

**Comment by william-silversmith** [comment] 2020-02-21 23:21
I'm not sure this was the cause of the segfault, but this issue would certainly need to be solved: https://github.com/seung-lab/dijkstra3d/issues/9

**Comment by william-silversmith** [comment] 2020-02-22 02:36
Hi again Varun,

I just released dijkstra3d==1.4.1 which should support 64 bit addressable arrays. Not sure if this will solve the problem completely, but it'll solve part of it. Note that this significantly the memory requirement for that part of Kimimaro's algorithm.

**Comment by william-silversmith** [comment] 2020-02-22 04:21
I fixed a second algorithm in Kimimaro that was segfaulting on large images. https://github.com/seung-lab/kimimaro/pull/42 This is available in release 1.3.1

**Comment by william-silversmith** [comment] 2020-02-22 05:16
I released a second set of fixed algorithms in 1.3.2 but I'm still seeing segfaults. It will take some time to debug this unfortunately...

**Comment by vkkhare** [comment] 2020-02-22 17:03
So I tested this with new dependencies and still got the error. Some boxes gave me segmentation fault while others gave a bus error. I will try running with a smaller box size comparable to yours

**Comment by william-silversmith** [comment] 2020-02-22 17:05
I ran a modified version last night so I could see where it was dying and
it looked like it was in the middle of the distance transform near the
beginning of the algorithm.

One more algo to update 😭

**Comment by vkkhare** [comment] 2020-02-22 17:05
I see thanks for the help so I should go with smaller boxes for the time now or I can go with the updated versions? @william-silversmith

**Comment by william-silversmith** [comment] 2020-02-22 17:07
You'll have to use a smaller box for now unfortunately. It's fine to use
the updated versions - they're technically more capable you just won't get
to use that heightened capability until it's uniform across all the
packages

**Comment by vkkhare** [comment] 2020-02-22 17:12
Okay I get it. Since the limit is with 32 bit addressing I think I can go to `(1872, 1872, 426)=1492867584` which would be less than 32 bit max limit of 2147483647?

**Comment by william-silversmith** [comment] 2020-02-22 17:17
This is likely the case. With the edt I thought I had already fixed this,
so it could end up being a problem with float precision or something like
that or a weird interaction between signed and unsigned integers.  Give it
a shot and see what happens.

**Comment by vkkhare** [comment] 2020-02-22 18:40
So I tried with having smaller boxes but now I run into `OSError: [Errno 28] No space left on device`  I searched on internet and found that temporary directory might be the cause and I manually specified `multiprocessing.process.current_process()._config['tempdir']` Still no benefit. I also tried restricting parallel to 2 instead of 0. None helped

**Comment by william-silversmith** [comment] 2020-02-22 20:29
That happens when you run out of memory. I would go with parallel 1 if
you're using huge chunks. I'd only use parallel with small boxes like
512x512x512

**Comment by vkkhare** [comment] 2020-02-23 12:24
I tried with smaller boxes and setting parallel=1 I get bus error in that case. I profiled my code and it is only the kimimaro sep causing the bus error.
```
    skeletons = kimimaro.skeletonize(
       cubeData, 
       teasar_params=teasar_params, 
       anisotropy=vox_size, # in nanometers
       dust_threshold=1000, # in voxels
       progress=progress,
       fix_branching=True,
       fix_borders=True, # default True
       parallel=0
    )
```

**Comment by william-silversmith** [comment] 2020-02-23 16:23
Hmm could you try a size that's 512x512x512? If you still get a bus error
something else is going on.

**Comment by vkkhare** [comment] 2020-02-23 20:01
I tried this as well (624*624*142) Still getting bus error

**Comment by william-silversmith** [comment] 2020-02-23 20:10
Hmm that's really weird. Can you try installing from source instead of
using the binaries? You can do

pip install kimimaro --no-cache-dir --no-binaries :all:

Or something approximating that.

I've never had an issue in this regime before.

**Comment by william-silversmith** [comment] 2020-02-24 21:53
I just released `edt==2.0.1` which supports much larger arrays (probably 63 bit). I'm testing with Kimimaro to see if it can trace a large cube now.

**Comment by william-silversmith** [comment] 2020-02-24 22:45
Running Kimimaro on 3000x3000x800 and seeing memory spike to at least 409 GB. Not sure what's causing it but at least it's not crashing. ^_^

**Comment by william-silversmith** [comment] 2020-02-24 22:52
I think it might be the soma centroid code. If you disable soma detection, you'll probably not run into that.

**Comment by vkkhare** [comment] 2020-03-07 00:06
I was able to run it finally. Seems multiprocessing was causing the bus error. 

> I tried this as well (624x2 x 624x2 x 142) Still getting bus error

**Comment by william-silversmith** [comment] 2020-03-07 00:55
Interesting! Were you using `parallel=N` or some separate multiprocessing? Unless you are careful, multiprocessing can make lots of copies of data under the hood. Kimimaro makes sure to use shared memory, but it only parallelizes over labels and it sounds like you have only one label.

**Comment by vkkhare** [comment] 2020-03-07 13:18
I was using parallel=0 though I tried with parallel=1 as well

**Comment by william-silversmith** [comment] 2020-03-10 05:13
I released another fix to the dijkstra3d library today. If you're still having trouble, see if you can process a bigger chunk with parallel==1 after upgrading.

**Comment by william-silversmith** [comment] 2020-07-13 19:01
I'm going to close this assuming the problem is fixed now. Please reopen if you're still having problems!

**Closed by william-silversmith** 2020-07-13 19:01 UTC
Labels: bug
